# Generated by Django 5.0.6 on 2024-05-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
